files_tags = [
    "listfilepages/datafilestagpages/datafilesability.html",
    "listfilepages/datafilestagpages/datafilesabilitycategory.html",
    "listfilepages/datafilestagpages/datafilesarmorproficiencies.html",
    "listfilepages/datafilestagpages/datafilesclasses.html",
    "listfilepages/datafilestagpages/datafilescompanionmodifiers.html",
    "listfilepages/datafilestagpages/datafilesdeities.html",
    "listfilepages/datafilestagpages/datafilesdomains.html",
    "listfilepages/datafilestagpages/datafilesequipment.html",
    "listfilepages/datafilestagpages/datafilesequipmentmodifiers.html",
    "listfilepages/datafilestagpages/datafilesfeats.html",
    "listfilepages/datafilestagpages/datafilesinstall.html",
    "listfilepages/datafilestagpages/datafileslanguages.html",
    "listfilepages/datafilestagpages/datafilespcc.html",
    "listfilepages/datafilestagpages/datafilesraces.html",
    "listfilepages/datafilestagpages/datafilesshieldproficiencies.html",
    "listfilepages/datafilestagpages/datafilesskills.html",
    "listfilepages/datafilestagpages/datafilesspells.html",
    "listfilepages/datafilestagpages/datafilesstartingkits.html",
    "listfilepages/datafilestagpages/datafilestags.html",
    "listfilepages/datafilestagpages/datafilestemplates.html",
    "listfilepages/datafilestagpages/datafilesweaponproficiencies.html",
    "listfilepages/globalfilestagpages/globalfilesadd.html",
    "listfilepages/globalfilestagpages/globalfilesbonus.html",
    "listfilepages/globalfilestagpages/globalfileschoose.html",
    "listfilepages/globalfilestagpages/globalfilesdefine.html",
    "listfilepages/globalfilestagpages/globalfilesformulas.html",
    "listfilepages/globalfilestagpages/globalfileskey.html",
    "listfilepages/globalfilestagpages/globalfilesother.html",
    "listfilepages/globalfilestagpages/globalfilesprexxx.html",
    "listfilepages/globalfilestagpages/globalfilestype.html",
    "listfilepages/globalfilestagpages/globalfilesvariables.html",
    "listfilepages/systemfilestagpages/gamemodeequipicons.html",
    "listfilepages/systemfilestagpages/gamemodeequipmentslots.html",
    "listfilepages/systemfilestagpages/gamemodelevel.html",
    "listfilepages/systemfilestagpages/gamemodeloadlist.html",
    "listfilepages/systemfilestagpages/gamemodelocationslist.html",
    "listfilepages/systemfilestagpages/gamemodemigrationlist.html",
    "listfilepages/systemfilestagpages/gamemodemiscinfolist.html",
    "listfilepages/systemfilestagpages/gamemodepointbuymethodlist.html",
    "listfilepages/systemfilestagpages/gamemoderules.html",
    "listfilepages/systemfilestagpages/gamemodestatsandcheckslist.html",
    "listfilepages/systemfilestagpages/gamemodetips.html",
    "listfilepages/systemfilestagpages/systemfilesbiosettingslist.html",
    "listfilepages/systemfilestagpages/systemfilessizeadjustment.html",
    "listfilepages/systemfilestagpages/systemfilestraitslist.html",
]

# files_tags = [
#     "listfilepages/datafilestagpages/datafilespcc.html",
# ]

tag_files_human_names = {
    "datafilesability":                 " (Data: abilities.lst)",
    "datafilesabilitycategory":         " (Data: ability_categories.lst)",
    "datafilesarmorproficiencies":      " (Data: armor_proficiencies.lst)",
    "datafilesclasses":                 " (Data: classes.lst)",
    "datafilescompanionmodifiers":      " (Data: companion_mods.lst)",
    "datafilesdeities":                 " (Data: deities.lst)",
    "datafilesdomains":                 " (Data: domains.lst)",
    "datafilesequipment":               " (Data: equipment.lst)",
    "datafilesequipmentmodifiers":      " (Data: equipment_modifiers.lst)",
    "datafilesfeats":                   " (Data: feats.lst)",
    "datafilesinstall":                 " (Data: install.lst)",
    "datafileslanguages":               " (Data: languages.lst)",
    "datafilespcc":                     " (Data: campaign.pcc)",
    "datafilesraces":                   " (Data: races.lst)",
    "datafilesshieldproficiencies":     " (Data: shield_proficiencies.lst)",
    "datafilesskills":                  " (Data: skills.lst)",
    "datafilesspells":                  " (Data: spells.lst)",
    "datafilesstartingkits":            " (Data: starting_kits.lst)",
    "datafilestags":                    "",
    "datafilestemplates":               " (Data: templates.lst)",
    "datafilesweaponproficiencies":     " (Data: weapon_proficiencies.lst)",
    "globalfilesadd":                   " (Global: ADD)",
    "globalfilesbonus":                 " (Global: BONUS)",
    "globalfileschoose":                " (Global: CHOOSE)",
    "globalfilesdefine":                " (Global: DEFINE)",
    "globalfilesformulas":              "",
    "globalfileskey":                   "",
    "globalfilesother":                 " (Global: OTHER)",
    "globalfilesprexxx":                " (Global: PRErequisite)",
    "globalfilestype":                  "",
    "globalfilesvariables":             "",
    "gamemodeequipicons":               " (Game Mode: equipicons.lst)",
    "gamemodeequipmentslots":           " (Game Mode: equipmentslots.lst)",
    "gamemodelevel":                    " (Game Mode: level.lst)",
    "gamemodeloadlist":                 " (Game Mode: load.lst",
    "gamemodelocationslist":            " (Game Mode: bio/locations.lst)",
    "gamemodemigrationlist":            " (Game Mode: migration.lst)",
    "gamemodemiscinfolist":             " (Game Mode: miscinfo.lst)",
    "gamemodepointbuymethodlist":       " (Game Mode: pointbuymethods_system.lst)",
    "gamemoderules":                    " (Game Mode: rules.lst)",
    "gamemodestatsandcheckslist":       " (Game Mode: statsandchecks.lst)",
    "gamemodetips":                     " (Game Mode: tips.txt)",
    "systemfilesbiosettingslist":       " (Game Mode: bio/biosettings.lst)",
    "systemfilessizeadjustment":        " (Game Mode: sizeAdjustment.lst)",
    "systemfilestraitslist":            " (Game Mode: bio/traits.lst)",
}

files_no_tags = [
    "greetings.html",
    "standards.html",
    "acknowledgments/acknowledgments.html",
    "acknowledgments/bod.html",
    "acknowledgments/bylaws.html",
    "acknowledgments/contributors.html",
    "acknowledgments/gnulicense.html",
    "acknowledgments/licenses.html",
    "acknowledgments/ogllicense.html",
    "acknowledgments/outputsheets.html",
    "acknowledgments/publishersandsources.html",
    "acknowledgments/skinlflicense.html",
    "faqpages/faqcharcreateissues.html",
    "faqpages/faqcommunity.html",
    "faqpages/faqdatasources.html",
    "faqpages/faqiwannahelp.html",
    "faqpages/faqmonkeyteamsexplained.html",
    "faqpages/faqotherissues.html",
    "faqpages/faqoutofmemoryandjavaissues.html",
    "faqpages/faqprintingissues.html",
    "faqpages/faqsectionheading.html",
    "faqpages/faqskinningpcgen.html",
    "faqpages/faqstartupinstallissues.html",
    "faqpages/faqsubmittingabugreport.html",
    "faqpages/faqsubmittingafeaturerequest.html",
    "faqpages/faqwotcoglsrdd20.html",
    "faqpages/faqyahooandhelping.html",
    "freemarkeroutputpages/creatingasheet.html",
    "freemarkeroutputpages/freemarkerintro.html",
    "freemarkeroutputpages/freemarkeroutputsectionheading.html",
    "freemarkeroutputpages/pcgenfunctions.html",
    "gmgen/characters.html",
    "gmgen/charactersheet.html",
    "gmgen/dicebag.html",
    "gmgen/encounter.html",
    "gmgen/experience.html",
    "gmgen/gmgen.html",
    "gmgen/initiative.html",
    "gmgen/network.html",
    "gmgen/notes.html",
    "gmgen/overlandtravel.html",
    "gmgen/preferences.html",
    "gmgen/randomnames.html",
    "installationpages/installationjava.html",
    "installationpages/installationpcgen.html",
    "installationpages/installationsectionheading.html",
    "installationpages/requirements.html",
    "installationpages/upgradepcgen.html",
    "listfilepages/listfiledatadevelopment.html",
    "listfilepages/listfilegamemodefiles.html",
    "listfilepages/listfileglobaldatafiles.html",
    "listfilepages/listfileimportanttoknow.html",
    "listfilepages/listfileLSTstandards.html",
    "listfilepages/listfileLSTwalkthrough.html",
    "listfilepages/listfilesectionheading.html",
    "listfilepages/listfilesystemfiles.html",
    "listfilepages/listfiletagindex.html",
    "listfilepages/listfiletagsbydatafile.html",
    "listfilepages/listindex.html",
    "listfilepages/lstfileclass/lfc_lesson00_homebrew.html",
    "listfilepages/lstfileclass/lfc_lesson01_pcc.html",
    "listfilepages/lstfileclass/lfc_lesson02_pcc.html",
    "listfilepages/lstfileclass/lfc_lesson03_race1.html",
    "listfilepages/lstfileclass/lfc_lesson04_race2.html",
    "listfilepages/lstfileclass/lfc_lesson05_race3.html",
    "listfilepages/lstfileclass/lfc_lesson06_race4.html",
    "listfilepages/lstfileclass/lfc_lesson07_spells.html",
    "listfilepages/lstfileclass/lfc_lesson08_biosettings.html",
    "listfilepages/lstfileclass/lfc_lesson09_weaponprofs.html",
    "listfilepages/lstfileclass/lfc_lesson10_languages.html",
    "listfilepages/lstfileclass/lfc_lesson11_kits_default_monster.html",
    "listfilepages/lstfileclass/lfc_lesson12_feat1.html",
    "listfilepages/lstfileclass/lfc_lesson13_feat2.html",
    "listfilepages/lstfileclass/lfc_lesson14_deities.html",
    "listfilepages/lstfileclass/lfc_lesson15_domains1.html",
    "listfilepages/lstfileclass/lfc_lesson16_domains2.html",
    "listfilepages/lstfileclass/lfc_lesson17_converting_feats_to_abilities.html",
    "listfilepages/lstfileclass/lfc_lesson18_HD_LEVEL_conversion.html",
    "listfilepages/lstfileclass/lfc_lesson19_companion_mods.html",
    "listfilepages/lstfileclass/lfc_style_guide.html",
    "listfilepages/lstfileclass/lstfileclass_heading.html",
    "listfilepages/rulesguide/game_rules_implement_heading.html",
    "listfilepages/rulesguide/game_rules_reading_instructions.html",
    "listfilepages/rulesguide/grig_abilities_by_skill_ranks.html",
    "listfilepages/rulesguide/grig_negative_levels.html",
    "listfilepages/rulesguide/grig_priesthoods1.html",
    "menupages/menusectionheading.html",
    "menupages/debug/debugoption.html",
    "menupages/edit/editaddkitoptions.html",
    "menupages/edit/editequipmentsetoptions.html",
    "menupages/edit/editgenerateoptions.html",
    "menupages/edit/editsectionheading.html",
    "menupages/edit/edittemporarybonusoptions.html",
    "menupages/file/fileaddkitoptions.html",
    "menupages/file/fileexportoptions.html",
    "menupages/file/fileexportpdf.html",
    "menupages/file/fileexportstandard.html",
    "menupages/file/fileexporttxt.html",
    "menupages/file/filenpcgen.html",
    "menupages/file/filenpcgendatafiles.html",
    "menupages/file/filenpcgennpccreation.html",
    "menupages/file/filepartyoptions.html",
    "menupages/file/filesectionheading.html",
    "menupages/help/helpaboutpcgen.html",
    "menupages/help/helpsectionheading.html",
    "menupages/settings/settingscampaignoption.html",
    "menupages/settings/settingsgamemodeoption.html",
    "menupages/settings/settingspreferencesoption.html",
    "menupages/settings/settingssectionheading.html",
    "menupages/settings/settingssourceloadingoption.html",
    "menupages/settings/appearance/appearancecolors.html",
    "menupages/settings/appearance/appearancedisplay.html",
    "menupages/settings/appearance/appearancelevelup.html",
    "menupages/settings/appearance/appearancelookandfeel.html",
    "menupages/settings/appearance/appearancesectionheading.html",
    "menupages/settings/appearance/appearancetabs.html",
    "menupages/settings/character/characterabilityscoreoption.html",
    "menupages/settings/character/characterhitpointsoption.html",
    "menupages/settings/character/characterhouserulesoption.html",
    "menupages/settings/character/charactermonstersoption.html",
    "menupages/settings/character/characterpurchasemethodoption.html",
    "menupages/settings/character/charactersectionheading.html",
    "menupages/settings/pcgen/pcgenequipoption.html",
    "menupages/settings/pcgen/pcgenlanguage.html",
    "menupages/settings/pcgen/pcgenlocation.html",
    "menupages/settings/pcgen/pcgenoutput.html",
    "menupages/settings/pcgen/pcgensectionheading.html",
    "menupages/settings/pcgen/pcgensources.html",
    "menupages/settings/plugins/plugins_charactersheet.html",
    "menupages/sources/sourcesinstalldataoptions.html",
    "menupages/sources/sourcesloadoptions.html",
    "menupages/sources/sourcessectionheading.html",
    "menupages/sources/sourcesselectionoptions.html",
    "menupages/tools/toolsdebugingoptions.html",
    "menupages/tools/toolsfiltercustom.html",
    "menupages/tools/toolsfilteredit.html",
    "menupages/tools/toolsfilteropen.html",
    "menupages/tools/toolsfilteroption.html",
    "menupages/tools/toolsinstalldataset.html",
    "menupages/tools/toolslisteditors.html",
    "menupages/tools/toolslstconverter.html",
    "menupages/tools/toolssectionheading.html",
    "menupages/tools/toolstreasuregenerator.html",
    "menupages/tools/class/classeditorabilitiestab.html",
    "menupages/tools/class/classeditoradvancedtab.html",
    "menupages/tools/class/classeditorbasetab.html",
    "menupages/tools/class/classeditorlanguagestab.html",
    "menupages/tools/class/classeditorlevelstab.html",
    "menupages/tools/class/classeditorsectionheading.html",
    "menupages/tools/class/classeditorskillstab.html",
    "menupages/tools/class/classeditorweaponstab.html",
    "menupages/tools/deity/deityeditoradvancedtab.html",
    "menupages/tools/deity/deityeditorbasetab.html",
    "menupages/tools/deity/deityeditordomainstab.html",
    "menupages/tools/deity/deityeditorfollowerstab.html",
    "menupages/tools/deity/deityeditorlanguagestab.html",
    "menupages/tools/deity/deityeditorracestab.html",
    "menupages/tools/deity/deityeditorsectionheading.html",
    "menupages/tools/deity/deityeditorskillstab.html",
    "menupages/tools/deity/deityeditorweaponstab.html",
    "menupages/tools/domain/domaineditoradvancedtab.html",
    "menupages/tools/domain/domaineditorbasetab.html",
    "menupages/tools/domain/domaineditorlanguagestab.html",
    "menupages/tools/domain/domaineditorsectionheading.html",
    "menupages/tools/domain/domaineditorskillstab.html",
    "menupages/tools/domain/domaineditorweaponstab.html",
    "menupages/tools/feat/featseditoradvancedtab.html",
    "menupages/tools/feat/featseditorbasetab.html",
    "menupages/tools/feat/featseditorlanguagestab.html",
    "menupages/tools/feat/featseditorsectionheading.html",
    "menupages/tools/feat/featseditorskillstab.html",
    "menupages/tools/feat/featseditorweaponstab.html",
    "menupages/tools/language/languageeditoradvancedtab.html",
    "menupages/tools/language/languageeditorbasetab.html",
    "menupages/tools/language/languageeditorsectionheading.html",
    "menupages/tools/preferences/preferencesapearanceoptions.html",
    "menupages/tools/preferences/preferencesappearanceoptions.html",
    "menupages/tools/preferences/preferencescharacteroptions.html",
    "menupages/tools/preferences/preferencesgamemodeoptions.html",
    "menupages/tools/preferences/preferencespcgenoptions.html",
    "menupages/tools/preferences/preferencespluginoptions.html",
    "menupages/tools/preferences/preferencessectionheading.html",
    "menupages/tools/race/raceeditoradvancedtab.html",
    "menupages/tools/race/raceeditoragetab.html",
    "menupages/tools/race/raceeditorappearancetab.html",
    "menupages/tools/race/raceeditorbasetab.html",
    "menupages/tools/race/raceeditorbonuslangtab.html",
    "menupages/tools/race/raceeditorclassestab.html",
    "menupages/tools/race/raceeditorfeatstab.html",
    "menupages/tools/race/raceeditorlanguagestab.html",
    "menupages/tools/race/raceeditormovementtab.html",
    "menupages/tools/race/raceeditornaturalweaponstab.html",
    "menupages/tools/race/raceeditorsectionheading.html",
    "menupages/tools/race/raceeditorskillstab.html",
    "menupages/tools/race/raceeditortemplatestab.html",
    "menupages/tools/race/raceeditorvirtualfeatstab.html",
    "menupages/tools/race/raceeditorvisiontab.html",
    "menupages/tools/race/raceeditorweaponstab.html",
    "menupages/tools/skill/skilleditoradvancedtab.html",
    "menupages/tools/skill/skilleditorbasetab.html",
    "menupages/tools/skill/skilleditorclassestab.html",
    "menupages/tools/skill/skilleditorlanguagestab.html",
    "menupages/tools/skill/skilleditorsectionheading.html",
    "menupages/tools/skill/skilleditorskillstab.html",
    "menupages/tools/skill/skilleditorsynergytab.html",
    "menupages/tools/skill/skilleditorweaponstab.html",
    "menupages/tools/source/sourceeditoradvancedtab.html",
    "menupages/tools/source/sourceeditorbasetab.html",
    "menupages/tools/source/sourceeditorfiletypetab.html",
    "menupages/tools/source/sourceeditorsectionheading.html",
    "menupages/tools/spell/spelleditoradvancedtab.html",
    "menupages/tools/spell/spelleditorbase2tab.html",
    "menupages/tools/spell/spelleditorbasetab.html",
    "menupages/tools/spell/spelleditorclassestab.html",
    "menupages/tools/spell/spelleditordomainstab.html",
    "menupages/tools/spell/spelleditorsectionheading.html",
    "menupages/tools/template/templateeditorabilitiestab.html",
    "menupages/tools/template/templateeditoradvancedtab.html",
    "menupages/tools/template/templateeditorbasetab.html",
    "menupages/tools/template/templateeditorbonuslangtab.html",
    "menupages/tools/template/templateeditorclassestab.html",
    "menupages/tools/template/templateeditorfeatstab.html",
    "menupages/tools/template/templateeditorlanguagestab.html",
    "menupages/tools/template/templateeditormovementtab.html",
    "menupages/tools/template/templateeditorsectionheading.html",
    "menupages/tools/template/templateeditorskillstab.html",
    "menupages/tools/template/templateeditortemplatestab.html",
    "menupages/tools/template/templateeditorweaponstab.html",
    "outputsheetpages/csheetexamplehtml.html",
    "outputsheetpages/csheetexampleoutput.html",
    "outputsheetpages/outputsheetbasexml.html",
    "outputsheetpages/outputsheetsectionheading.html",
    "outputsheetpages/outputsheetspdf.html",
    "outputsheetpages/outputsheetsstd.html",
    "outputsheetpages/outputsheetstokensused.html",
    "outputsheetpages/outputsheetstutorial.html",
    "outputsheetpages/tokens/outputsheettokensgeneral.html",
    "outputsheetpages/tokens/outputsheettokensmisc.html",
    "outputsheetpages/tokens/outputsheettokenssaves-hp.html",
    "outputsheetpages/tokens/outputsheettokensspecialability.html",
    "outputsheetpages/tokens/outputsheettokensspell.html",
    "outputsheetpages/tokens/outputsheettokensweapon.html",
    "sourcehelp/pcgen_ogc_help.html",
    "sourcehelp/pcgen_ogc_psicrystal_hd.html",
    "sourcehelp/sourcehelp_sectionheading.html",
    "sourcehelp/4e_docs/4e_doc_sectionheading.html",
    "sourcehelp/fantasy/fantasy_header.html",
    "sourcehelp/fantasy/midnight_help.html",
    "sourcehelp/fantasy/pathfinder.html",
    "sourcehelp/fantasy/playersguidearcanis.html",
    "sourcehelp/fantasy/relicsrituals.html",
    "sourcehelp/fantasy/rsrd_help.html",
    "sourcehelp/fantasy/sorcery_and_steam_help.html",
    "sourcehelp/fantasy/srd_help.html",
    "sourcehelp/modern/msrd_future_help.html",
    "sourcehelp/modern/msrd_help.html",
    "sourcehelp/pathfinder/pathfinder_header.html",
    "sourcehelp/pathfinder/pathfinder_rpg.html",
    "sourcehelp/pathfinder/pathfinder_traits.html",
    "sourcehelp/spycraft/shadowforce_archer_help.html",
    "sourcehelp/spycraft/spycraft_help.html",
    "tabpages/tabcharactersheet.html",
    "tabpages/tabclasses.html",
    "tabpages/tabcompanions.html",
    "tabpages/tabdescription.html",
    "tabpages/tabdomains.html",
    "tabpages/tabfeatsandabilities.html",
    "tabpages/tabinventory.html",
    "tabpages/tabraces.html",
    "tabpages/tabsectionheading.html",
    "tabpages/tabskills.html",
    "tabpages/tabspells.html",
    "tabpages/tabsummary.html",
    "tabpages/tabtemplates.html",
    "tabpages/tabtemporarybonuses.html",
    "tabpages/inventory/inventoryequipping.html",
    "tabpages/inventory/inventorygear.html",
    "tabpages/inventory/inventorysectionheading.html",
    "tabpages/players/playerssectionheading.html",
    "tabpages/players/tabability.html",
    "tabpages/players/tabpreview.html",
    "tabpages/source/buttoncustomise.html",
    "tabpages/source/sourcesectionheading.html",
    "walkthroughpages/toolbarquickicons.html",
    "walkthroughpages/walkthroughcreatecharacter.html",
    "walkthroughpages/walkthroughcreatenew.html",
    "walkthroughpages/walkthroughheadingstartup.html",
    "walkthroughpages/walkthroughloadcampaign.html",
    "walkthroughpages/walkthroughloadcampaignadvanced.html",
    "walkthroughpages/walkthroughloadcampaignbasic.html",
    "walkthroughpages/walkthroughprintnew.html",
    "walkthroughpages/walkthroughsectionheading.html",
]

# files_no_tags = []

all_files = files_no_tags + files_tags
