files_tags = [
    "list/data/ability.html",
    "list/data/abilitycategory.html",
    "list/data/armor-proficiencies.html",
    "list/data/classes.html",
    "list/data/companionmodifiers.html",
    "list/data/deities.html",
    "list/data/domains.html",
    "list/data/equipment.html",
    "list/data/equipmentmodifiers.html",
    "list/data/feats.html",
    "list/data/install.html",
    "list/data/languages.html",
    "list/data/pcc.html",
    "list/data/races.html",
    "list/data/shieldproficiencies.html",
    "list/data/skills.html",
    "list/data/spells.html",
    "list/data/startingkits.html",
    "list/data/tags.html",
    "list/data/templates.html",
    "list/data/weaponproficiencies.html",
    "list/global/add.html",
    "list/global/bonus.html",
    "list/global/choose.html",
    "list/global/define.html",
    "list/global/formulas.html",
    "list/global/key.html",
    "list/global/other.html",
    "list/global/pre.html",
    "list/global/type.html",
    "list/global/variables.html",
    "list/system/gamemode-equipicons.html",
    "list/system/gamemode-equipmentslots.html",
    "list/system/gamemode-level.html",
    "list/system/gamemode-load.html",
    "list/system/gamemode-locations.html",
    "list/system/gamemode-migration.html",
    "list/system/gamemode-miscinfo.html",
    "list/system/gamemode-pointbuymethod.html",
    "list/system/gamemode-rules.html",
    "list/system/gamemode-statsandchecks.html",
    "list/system/gamemode-tips.html",
    "list/system/biosettings.html",
    "list/system/sizeadjustment.html",
    "list/system/traits.html",
]

# files_tags = [
#     "listfilepages/datafilestagpages/datafilespcc.html",
# ]

tag_files_human_names = {
    "ability":                           " (Data: abilities.lst)",
    "abilitycategory":                   " (Data: ability_categories.lst)",
    "armorproficiencies":                " (Data: armor_proficiencies.lst)",
    "classes":                           " (Data: classes.lst)",
    "companionmodifiers":                " (Data: companion_mods.lst)",
    "deities":                           " (Data: deities.lst)",
    "domains":                           " (Data: domains.lst)",
    "equipment":                         " (Data: equipment.lst)",
    "equipmentmodifiers":                " (Data: equipment_modifiers.lst)",
    "feats":                             " (Data: feats.lst)",
    "install":                           " (Data: install.lst)",
    "languages":                         " (Data: languages.lst)",
    "pcc":                               " (Data: campaign.pcc)",
    "races":                             " (Data: races.lst)",
    "shieldproficiencies":               " (Data: shield_proficiencies.lst)",
    "skills":                            " (Data: skills.lst)",
    "spells":                            " (Data: spells.lst)",
    "startingkits":                      " (Data: starting_kits.lst)",
    "tags":                              "",
    "templates":                         " (Data: templates.lst)",
    "weaponproficiencies":               " (Data: weapon_proficiencies.lst)",
    "add":                               " (Global: ADD)",
    "bonus":                             " (Global: BONUS)",
    "choose":                            " (Global: CHOOSE)",
    "define":                            " (Global: DEFINE)",
    "formulas":                          "",
    "key":                               "",
    "other":                             " (Global: OTHER)",
    "pre":                               " (Global: PRErequisite)",
    "type":                              "",
    "variables":                         "",
    "gamemode-equipicons":               " (Game Mode: equipicons.lst)",
    "gamemode-equipmentslots":           " (Game Mode: equipmentslots.lst)",
    "gamemode-level":                    " (Game Mode: level.lst)",
    "gamemode-load":                     " (Game Mode: load.lst",
    "gamemode-locations":                " (Game Mode: bio/locations.lst)",
    "gamemode-migration":                " (Game Mode: migration.lst)",
    "gamemode-miscinfo":                 " (Game Mode: miscinfo.lst)",
    "gamemode-pointbuymethod":           " (Game Mode: pointbuymethods_system.lst)",
    "gamemode-rules":                    " (Game Mode: rules.lst)",
    "gamemode-statsandchecks":           " (Game Mode: statsandchecks.lst)",
    "gamemode-tips":                     " (Game Mode: tips.txt)",
    "biosettings":                       " (System: bio/biosettings.lst)",
    "sizeadjustment":                    " (System: sizeAdjustment.lst)",
    "traits":                            " (System: bio/traits.lst)",
}

files_no_tags = [
    "greetings.html",
    "standards.html",
    "credits/index.html",
    "credits/bod.html",
    "credits/bylaws.html",
    "credits/contributors.html",
    "credits/gnu-license.html",
    "credits/licenses.html",
    "credits/ogl-license.html",
    "credits/output-sheets.html",
    "credits/publishers-and-sources.html",
    "credits/skin-lf-license.html",
    "faq/char-create-issues.html",
    "faq/community.html",
    "faq/data-sources.html",
    "faq/i-want-to-help-make-datasets.html",
    "faq/monkey-teams-explained.html",
    "faq/other-issues.html",
    "faq/out-of-memory-and-java-issues.html",
    "faq/printing-issues.html",
    "faq/index.html",
    "faq/skinning-pcgen.html",
    "faq/startup-install-issues.html",
    "faq/bug-report.html",
    "faq/feature-request.html",
    "faq/wotc-ogl-srd-d20.html",
    "faq/yahooandhelping.html",
    "freemarker/creating-a-sheet.html",
    "freemarker/intro.html",
    "freemarker/index.html",
    "freemarker/pcgen-functions.html",
    "gmgen/characters.html",
    "gmgen/character-sheet.html",
    "gmgen/dice-bag.html",
    "gmgen/encounter.html",
    "gmgen/experience.html",
    "gmgen/gmgen.html",
    "gmgen/initiative.html",
    "gmgen/network.html",
    "gmgen/notes.html",
    "gmgen/overland-travel.html",
    "gmgen/preferences.html",
    "gmgen/random-names.html",
    "installation/java.html",
    "installation/pcgen.html",
    "installation/index.html",
    "installation/requirements.html",
    "installation/upgradepcgen.html",
    "list/data-development.html",
    "list/gamemode.html",
    "list/global.html",
    "list/important-to-know.html",
    "list/lst-standards.html",
    "list/lst-walkthrough.html",
    "list/index.html",
    "list/system.html",
    "list/tag-index.html",
    "list/tags-by-datafile.html",
    "list/list-index.html",
    "list/lst-file-class/00-homebrew.html",
    "list/lst-file-class/01-pcc.html",
    "list/lst-file-class/02-pcc.html",
    "list/lst-file-class/03-race-1.html",
    "list/lst-file-class/04-race-2.html",
    "list/lst-file-class/05-race-3.html",
    "list/lst-file-class/06-race-4.html",
    "list/lst-file-class/07-spells.html",
    "list/lst-file-class/08-biosettings.html",
    "list/lst-file-class/09-weaponproficiencies.html",
    "list/lst-file-class/10-languages.html",
    "list/lst-file-class/11-kits-default-monster.html",
    "list/lst-file-class/12-feat-1.html",
    "list/lst-file-class/13-feat-2.html",
    "list/lst-file-class/14-deities.html",
    "list/lst-file-class/15-domains-1.html",
    "list/lst-file-class/16-domains-2.html",
    "list/lst-file-class/17-converting-feats-to-abilities.html",
    "list/lst-file-class/18-hd-level-conversion.html",
    "list/lst-file-class/19-companion-mods.html",
    "list/lst-file-class/style-guide.html",
    "list/lst-file-class/index.html",
    "list/rules-guide/index.html",
    "list/rules-guide/reading-instructions.html",
    "list/rules-guide/grig-abilities-by-skill_ranks.html",
    "list/rules-guide/grig-negative-levels.html",
    "list/rules-guide/grig-priesthoods.html",
    "menu/index.html",
    "menu/debug/debug.html",
    "menu/edit/addkit.html",
    "menu/edit/equipmentset.html",
    "menu/edit/generate.html",
    "menu/edit/index.html",
    "menu/edit/temporary-bonus.html",
    "menu/file/addkit.html",
    "menu/file/export.html",
    "menu/file/export-pdf.html",
    "menu/file/export-standard.html",
    "menu/file/export-txt.html",
    "menu/file/npcgen.html",
    "menu/file/npcgen-datafiles.html",
    "menu/file/npcgen-npc-creation.html",
    "menu/file/party-options.html",
    "menu/file/index.html",
    "menu/help/about-pcgen.html",
    "menu/help/index.html",
    "menu/settings/campaign.html",
    "menu/settings/gamemode.html",
    "menu/settings/preferences.html",
    "menu/settings/index.html",
    "menu/settings/source-loading.html",
    "menu/settings/appearance/colors.html",
    "menu/settings/appearance/display.html",
    "menu/settings/appearance/levelup.html",
    "menu/settings/appearance/look-and-feel.html",
    "menu/settings/appearance/index.html",
    "menu/settings/appearance/tabs.html",
    "menu/settings/character/ability-score.html",
    "menu/settings/character/hitpoints.html",
    "menu/settings/character/house-rules.html",
    "menu/settings/character/monsters.html",
    "menu/settings/character/purchase-method.html",
    "menu/settings/character/index.html",
    "menu/settings/pcgen/equip.html",
    "menu/settings/pcgen/language.html",
    "menu/settings/pcgen/location.html",
    "menu/settings/pcgen/output.html",
    "menu/settings/pcgen/index.html",
    "menu/settings/pcgen/sources.html",
    "menu/settings/plugins/plugins-charactersheet.html",
    "menu/sources/install-data.html",
    "menu/sources/load.html",
    "menu/sources/index.html",
    "menu/sources/selection.html",
    "menu/tools/debugging.html",
    "menu/tools/filter-custom.html",
    "menu/tools/filter-edit.html",
    "menu/tools/filter-open.html",
    "menu/tools/filter-option.html",
    "menu/tools/install-dataset.html",
    "menu/tools/list-editors.html",
    "menu/tools/lst-converter.html",
    "menu/tools/index.html",
    "menu/tools/treasure-generator.html",
    "menu/tools/class-editor/abilities.html",
    "menu/tools/class-editor/advanced.html",
    "menu/tools/class-editor/base.html",
    "menu/tools/class-editor/languages.html",
    "menu/tools/class-editor/levels.html",
    "menu/tools/class-editor/index.html",
    "menu/tools/class-editor/skills.html",
    "menu/tools/class-editor/weapons.html",
    "menu/tools/deity-editor/advanced.html",
    "menu/tools/deity-editor/base.html",
    "menu/tools/deity-editor/domains.html",
    "menu/tools/deity-editor/followers.html",
    "menu/tools/deity-editor/languages.html",
    "menu/tools/deity-editor/races.html",
    "menu/tools/deity-editor/index.html",
    "menu/tools/deity-editor/skills.html",
    "menu/tools/deity-editor/weapons.html",
    "menu/tools/domain-editor/advanced.html",
    "menu/tools/domain-editor/base.html",
    "menu/tools/domain-editor/languages.html",
    "menu/tools/domain-editor/index.html",
    "menu/tools/domain-editor/skills.html",
    "menu/tools/domain-editor/weapons.html",
    "menu/tools/feat-editor/advanced.html",
    "menu/tools/feat-editor/base.html",
    "menu/tools/feat-editor/languages.html",
    "menu/tools/feat-editor/index.html",
    "menu/tools/feat-editor/skills.html",
    "menu/tools/feat-editor/weapons.html",
    "menu/tools/language-editor/advanced.html",
    "menu/tools/language-editor/base.html",
    "menu/tools/language-editor/index.html",
    "menu/tools/preferences/DUPLICATED.html",
    "menu/tools/preferences/appearance.html",
    "menu/tools/preferences/character.html",
    "menu/tools/preferences/gamemode.html",
    "menu/tools/preferences/pcgen.html",
    "menu/tools/preferences/plugin.html",
    "menu/tools/preferences/index.html",
    "menu/tools/race-editor/advanced.html",
    "menu/tools/race-editor/age.html",
    "menu/tools/race-editor/appearance.html",
    "menu/tools/race-editor/base.html",
    "menu/tools/race-editor/bonus-lang.html",
    "menu/tools/race-editor/classes.html",
    "menu/tools/race-editor/feats.html",
    "menu/tools/race-editor/languages.html",
    "menu/tools/race-editor/movement.html",
    "menu/tools/race-editor/natural-weapons.html",
    "menu/tools/race-editor/index.html",
    "menu/tools/race-editor/skills.html",
    "menu/tools/race-editor/templates.html",
    "menu/tools/race-editor/virtual-feats.html",
    "menu/tools/race-editor/vision.html",
    "menu/tools/race-editor/weapons.html",
    "menu/tools/skill-editor/advanced.html",
    "menu/tools/skill-editor/base.html",
    "menu/tools/skill-editor/classes.html",
    "menu/tools/skill-editor/languages.html",
    "menu/tools/skill-editor/index.html",
    "menu/tools/skill-editor/skills.html",
    "menu/tools/skill-editor/synergy.html",
    "menu/tools/skill-editor/weapons.html",
    "menu/tools/source-editor/advanced.html",
    "menu/tools/source-editor/base.html",
    "menu/tools/source-editor/filetype.html",
    "menu/tools/source-editor/index.html",
    "menu/tools/spell-editor/advanced.html",
    "menu/tools/spell-editor/base-cont.html",
    "menu/tools/spell-editor/base.html",
    "menu/tools/spell-editor/classes.html",
    "menu/tools/spell-editor/domains.html",
    "menu/tools/spell-editor/index.html",
    "menu/tools/template-editor/abilities.html",
    "menu/tools/template-editor/advanced.html",
    "menu/tools/template-editor/base.html",
    "menu/tools/template-editor/bonus-lang.html",
    "menu/tools/template-editor/classes.html",
    "menu/tools/template-editor/feats.html",
    "menu/tools/template-editor/languages.html",
    "menu/tools/template-editor/movement.html",
    "menu/tools/template-editor/index.html",
    "menu/tools/template-editor/skills.html",
    "menu/tools/template-editor/templates.html",
    "menu/tools/template-editor/weapons.html",
    "outputsheet/example-html.html",
    "outputsheet/example-output.html",
    "outputsheet/base-xml.html",
    "outputsheet/index.html",
    "outputsheet/pdf.html",
    "outputsheet/std.html",
    "outputsheet/tokens-used.html",
    "outputsheet/tutorial.html",
    "outputsheet/tokens/general.html",
    "outputsheet/tokens/misc.html",
    "outputsheet/tokens/saves-hp.html",
    "outputsheet/tokens/special-ability.html",
    "outputsheet/tokens/spell.html",
    "outputsheet/tokens/weapon.html",
    "source/pcgen-ogc-help.html",
    "source/pcgen-ogc-psicrystal-hd.html",
    "source/index.html",
    "source/4e-docs/index.html",
    "source/fantasy/fantasy-header.html",
    "source/fantasy/midnight.html",
    "source/fantasy/pathfinder.html",
    "source/fantasy/players-guide-arcanis.html",
    "source/fantasy/relics-rituals.html",
    "source/fantasy/rsrd.html",
    "source/fantasy/sorcery-and-steam.html",
    "source/fantasy/srd.html",
    "source/modern/msrd-future.html",
    "source/modern/msrd.html",
    "source/pathfinder/index.html",
    "source/pathfinder/rpg.html",
    "source/pathfinder/traits.html",
    "source/spycraft/shadowforce-archer.html",
    "source/spycraft/spycraft.html",
    "tab/character-sheet.html",
    "tab/classes.html",
    "tab/companions.html",
    "tab/description.html",
    "tab/domains.html",
    "tab/feats-and-abilities.html",
    "tab/inventory.html",
    "tab/races.html",
    "tab/index.html",
    "tab/skills.html",
    "tab/spells.html",
    "tab/summary.html",
    "tab/templates.html",
    "tab/temporary-bonuses.html",
    "tab/inventory/equipping.html",
    "tab/inventory/gear.html",
    "tab/inventory/index.html",
    "tab/players/index.html",
    "tab/players/ability.html",
    "tab/players/preview.html",
    "tab/source-tab/button-customise.html",
    "tab/source-tab/index.html",
    "walkthrough/toolbar-quick-icons.html",
    "walkthrough/create-character.html",
    "walkthrough/create-new.html",
    "walkthrough/initial-startup.html",
    "walkthrough/load-campaign.html",
    "walkthrough/load-campaign-advanced.html",
    "walkthrough/load-campaign-basic.html",
    "walkthrough/print-new.html",
    "walkthrough/index.html",
]

# files_no_tags = []

all_files = files_no_tags + files_tags
